site_name: USTC 2023 编译原理和技术
repo_name: ustc-compiler-principles/2023
repo_url: https://github.com/ustc-compiler-principles/2023
theme:
  name: 'material'
  palette:
    primary: 'black'
  language: 'zh'
  features:
    - content.code.copy
    - navigation.footer
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - mdx_truly_sane_lists
  - toc:
      permalink: true
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
extra_css:
  - css/extra.css
nav:
  - 首页: README.md
  - 课程平台介绍: exp_platform_intro/README.md
  - Lab0:
    - Lab0 简介: lab0/index.md
    - Linux 环境配置: lab0/linux.md
    - LLVM 等软件环境配置: lab0/software.md
    - Git 的使用: lab0/git.md
  - Lab1:
    - Lab1 简介: lab1/index.md
    - 正则表达式: lab1/正则表达式.md
    - Flex: lab1/flex.md
    - Bison: lab1/bison.md
    - 实验细节与要求: lab1/实验细节与要求.md
  - FAQ: faq/README.md
