site_name: USTC 2023 编译原理和技术
repo_name: ustc-compiler-principles/2023
repo_url: https://github.com/ustc-compiler-principles/2023
theme:
  name: 'material'
  palette:
    primary: 'black'
  language: 'zh'
  features:
    - content.code.copy
    - navigation.footer
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - mdx_truly_sane_lists
  - toc:
      permalink: true
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  - css/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
nav:
  - 首页: README.md
  - 课程平台介绍: exp_platform_intro/README.md
  - 公共文档:
    - Cminusf 语法语义介绍: common/cminusf.md
    - Light IR 简介: common/LightIR.md
    - C++ 介绍: common/simple_cpp.md
    - Logging 工具使用: common/logging.md
    - 龙芯汇编介绍: common/asm_intro.md
  - Lab0:
    - Lab0 简介: lab0/index.md
    - Linux 环境配置: lab0/linux.md
    - LLVM 等软件环境配置: lab0/software.md
    - Git 的使用: lab0/git.md
  - Lab1:
    - Lab1 简介: lab1/index.md
    - 正则表达式: lab1/正则表达式.md
    - Flex: lab1/Flex.md
    - Bison: lab1/Bison.md
    - 实验细节与要求: lab1/实验细节与要求.md
  - Lab2:
    - Lab2 简介: lab2/index.md
    - Light IR 预热: lab2/warmup.md
    - 访问者模式: lab2/visitor_pattern.md
    - IR 自动化生成: lab2/autogen.md
  - Lab3:
    - Lab3 简介: lab3/index.md
    - 后端环境配置: lab3/environment.md
    - 后端框架介绍: lab3/framework.md
    - Lab3 实验指导: lab3/guidance.md
  - FAQ: faq/README.md
